name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-wheels:
    name: Wheels / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: pypa/cibuildwheel@v2
        with:
          package-dir: python/

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/
